var savedplayerstats = {
	PlayerName: "Boogaloo",
	Nam: "Class",
	Abr: "aaa",
	Element: "Fire",
	
	stats: {
		Health:				0,
		HealthPts:			0,
		HealthPtsCost:		100,
		HealthPtsUpgNum:	0,
		HealthMod:			0,
		CurrentHealth:		0,
		BaseHealth:			0,
		Str: 				0,
		StrengthPts: 		0,
		StrengthPtsCost:	100,
		StrengthPtsUpgNum:	0,
		ItemsStrMod:		0,
		StrMod:				0,
		Acc: 				0,
		AccuracyPts:		0,
		AccuracyPtsCost:	100,
		AccuracyPtsUpgNum:	0,
		HitChance:			0,
		ItemsAccMod:		0,
		AccMod:				0,
		Arm:				0,
		ArmorPts:			0,
		ArmorPtsCost:		100,
		ArmorPtsUpgNum:		0,
		ItemsArmMod:		0,
		ArmMod:				0,
		Ref:				0,
		ReflexesPts:		0,
		ReflexesPtsCost:	100,
		ReflexesPtsUpgNum:	0,
		ItemsRefMod:		0,
		RefMod:				0,
		Mana:				0,
		MaxMana:			0,
		Managain:			0,
		ManagainAK:			0,
		ItemsManMod:		0,
		Cri:				0,
		ItemsCriMod:		0,
		Exp:				0,
		Level:				1,
		StatPts:			0,
		StatTotal:			0,
		Damage:				0,
		DamageDealt:		0,
		FocusStats:			[],
		AvoidedStat:		[],

		
	},
	Status: {
		poisoned: 	false,
		poisontime:		0,
		poisondamage:	0,
		
		burned:		false,
		burntime:	0,
		burndamage:	0,
		burnweak:	0,
		
		lvlup:		false,
		weakened:	false,
		weaktime:	0,
		weakweak:	0,
	},
	
	inv: {
		healthpotcount:	0,
		manapotcount:	0,
		Gold:			0,
		weapon: {
			Quality: 	"",
			QualityRank: 0,
			Name:		"",
			AtkBst:		0,
			AccBst: 	0,
			ArmBst: 	0,
			RefBst: 	0,
		},
		armor: {
			Quality: 	"",
			QualityRank: 0,
			Name:		"",
			AtkBst:		0,
			AccBst: 	0,
			ArmBst: 	0,
			RefBst: 	0,
		},
		shield: {
			Quality: 	"",
			QualityRank: 0,
			Name:		"",
			AtkBst:		0,
			AccBst: 	0,
			ArmBst: 	0,
			RefBst: 	0,		
		},
	}
		
}